// dev/src/components/organisms/Skills.vue
<template>
  <section class="skills" id="skills">
    <h1>Skills</h1>
    <div class="skills__table">
      <SkillCategory>
        <template v-slot:title>Markup</template>
        <template v-slot:content>
          <p>HTML5, CSS3, SCSS/SASS, Responsive Styling</p>
          <p>various libraries &amp; styling toolkits</p>
        </template>
      </SkillCategory>
      <SkillCategory>
        <template v-slot:title>JS &amp; more</template>
        <template v-slot:content>
          <p>ECMAScript 6+, TypeScript</p>
          <p>React/Redux, Vue.js/Vuex, Nuxt</p>
          <p>Node.js, Firebase</p>
          <p>GraphQL</p>
          <p>Basics of C#</p>
        </template>
      </SkillCategory>
      <SkillCategory>
        <template v-slot:title>Testing</template>
        <template v-slot:content>
          <p>Jest</p>
          <p>Enzyme</p>
          <p>testing-library</p>
        </template>
      </SkillCategory>
      <SkillCategory>
        <template v-slot:title>Tools</template>
        <template v-slot:content>
          <p>Webpack, Gulp</p>
          <p>ESLint</p>
          <p>Git</p>
          <p>Jira (+ other Atlassian products)</p>
          <p>Photoshop, inVision, Sketch etc.</p>
        </template>
      </SkillCategory>
      <SkillCategory>
        <template v-slot:title>Languages</template>
        <template v-slot:content>
          <p>Ukrainian - native</p>
          <p>English - fluent</p>
          <p>Russian - fluent</p>
          <p>Polish - intermediate+</p>
          <p>Portuguese - beginner</p>
        </template>
      </SkillCategory>
    </div>
  </section>
</template>

<script>
import SkillCategory from '../molecules/SkillCategory.vue';

export default {
  name: 'Skills',
  components: {
    SkillCategory
  }
}
</script>

<style scoped lang="scss">
  @import '@/assets/mixins.scss';
  @import '@/assets/global.scss';

  .skills {
    @include FWsection();
    justify-content: flex-start;
    flex-direction: column;
    padding: 10em 0;

    h1 {
      @include largeHeading();
    }

    &__table {
      margin-top: 3.5em;
      padding: 0 1.5em;
      perspective: 1000px;
    }

    @media (min-width: $mobile-breakpoint) {
      &__table {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        padding: 0 3em;

        & > * {
          flex: 1 0 21%;
          max-width: 260px;
        }
      }
    }
  }
</style>

// src/components/Skills/Skills.jsx
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLongArrowAltDown } from "@fortawesome/free-solid-svg-icons";

import { bgColor4 } from "styles/theme";
import { ArrowDown } from "styles/common";

import {
  SkillsWrapper,
  SkillsTable,
  SkillsRow,
  SkillsSection,
  SkillsContent,
} from "./Skills.styles";

const Skills = () => {
  return (
    <SkillsWrapper id="skills" bgColor={bgColor4}>
      <h1>Skills</h1>
      <SkillsTable>
        <SkillsRow>
          <SkillsSection>markup</SkillsSection>
          <SkillsContent>
            <p>HTML5, CSS3, SCSS/SASS, Responsive Styling</p>
            <p>various libraries & styling toolkits</p>
          </SkillsContent>
        </SkillsRow>
        <SkillsRow>
          <SkillsSection>JS & more</SkillsSection>
          <SkillsContent>
            <p>ECMAScript 6+, TypeScript, React/Redux, Vue.js/Vuex, Nuxt</p>
            <p>Node.js, Firebase</p>
            <p>
              <small>GraphQL</small>
            </p>
            <p>Chrome Extension Development</p>
          </SkillsContent>
        </SkillsRow>
        <SkillsRow>
          <SkillsSection>tools</SkillsSection>
          <SkillsContent>
            <p>Webpack, Gulp</p>
            <p>ESLint</p>
            <p>Git</p>
          </SkillsContent>
        </SkillsRow>
        <SkillsRow>
          <SkillsSection>unit testing</SkillsSection>
          <SkillsContent>
            <p>Jest + Enzyme, Mocha, react-testing-library</p>
          </SkillsContent>
        </SkillsRow>
        <SkillsRow>
          <SkillsSection>other</SkillsSection>
          <SkillsContent>
            <p>Jira (+ other Atlassian products)</p>
            <p>Photoshop, inVision, Sketch etc.</p>
          </SkillsContent>
        </SkillsRow>
      </SkillsTable>
      <SkillsTable sub>
        <SkillsRow>
          <SkillsSection>languages</SkillsSection>
          <SkillsContent>
            <p>Ukrainian, Russian - mother tongues</p>
            <p>English - fluent</p>
            <p>Polish - intermediate+</p>
            <p>German - beginner</p>
          </SkillsContent>
        </SkillsRow>
      </SkillsTable>
      <ArrowDown side="bottom" text="personal & contacts" href="#personal">
        <FontAwesomeIcon icon={faLongArrowAltDown} />
      </ArrowDown>
    </SkillsWrapper>
  );
};

export default Skills;
